### PR TITLE
Mariadb  10.5 upgrade

### PR DESCRIPTION
**Pull request by EugeneKorolevich**

### CODE REVIEW

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!

**Comment by EugeneKorolevich** [comment]
@googlebot I consent!

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!

**Review by armandomiani — APPROVED** [review]

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!

**Comment by EugeneKorolevich** [comment]
@googlebot I signed it!'

**Pull request merged**
